export const APP_CLIENT_ID = Number(import.meta.env.PUBLIC_APP_CLIENT_ID);

export const DEFAULT_MAINNET_NOUNS_TOKEN_ADDRESS = import.meta.env
  .PUBLIC_MAINNET_NOUNS_TOKEN_ADDRESS;
export const DEFAULT_SEPOLIA_NOUNS_TOKEN_ADDRESS = import.meta.env
  .PUBLIC_SEPOLIA_NOUNS_TOKEN_ADDRESS;
